# -*- coding: utf-8 -*-
"""mymodule.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11TnjuVobDnndf90mtU6v8uqirLKhxL_u
"""

def greeting(name):
  print("Hello, " + name)

person1 = {
  "name": "Raj",
  "age": 16,
  "country": "India"
}

"""# **Import From Module**

You can choose to import only parts from a module, by using the from keyword.
"""

# The module named mymodule has one function and one dictionary:

def greeting(name):
  print("Hello, " + name)

person1 = {
  "name": "Raj",
  "age": 16,
  "country": "India"
}

from mymodule import person1

print (person1["age"])